apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: adxclusters.adx-mon.azure.com
spec:
  group: adx-mon.azure.com
  names:
    kind: ADXCluster
    listKind: ADXClusterList
    plural: adxclusters
    singular: adxcluster
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alerters.adx-mon.azure.com
spec:
  group: adx-mon.azure.com
  names:
    kind: Alerter
    listKind: AlerterList
    plural: alerters
    singular: alerter
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alertrules.adx-mon.azure.com
spec:
  group: adx-mon.azure.com
  names:
    kind: AlertRule
    listKind: AlertRuleList
    plural: alertrules
    singular: alertrule
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                database:
                  type: string
                query:
                  type: string
                interval:
                  type: string
                destination:
                  type: string
                criteria:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                autoMitigateAfter:
                  type: string
                criteriaExpression:
                  type: string
              required:
                - query
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: collectors.adx-mon.azure.com
spec:
  group: adx-mon.azure.com
  names:
    kind: Collector
    listKind: CollectorList
    plural: collectors
    singular: collector
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: functions.adx-mon.azure.com
spec:
  group: adx-mon.azure.com
  names:
    kind: Function
    listKind: FunctionList
    plural: functions
    singular: function
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                body:
                  type: string
                database:
                  type: string
                criteriaExpression:
                  type: string
              required:
                - body
                - database
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingestors.adx-mon.azure.com
spec:
  group: adx-mon.azure.com
  names:
    kind: Ingestor
    listKind: IngestorList
    plural: ingestors
    singular: ingestor
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managementcommands.adx-mon.azure.com
spec:
  group: adx-mon.azure.com
  names:
    kind: ManagementCommand
    listKind: ManagementCommandList
    plural: managementcommands
    singular: managementcommand
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                body:
                  type: string
                database:
                  type: string
              required:
                - body
                - database
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: metricsexporters.adx-mon.azure.com
spec:
  group: adx-mon.azure.com
  names:
    kind: MetricsExporter
    listKind: MetricsExporterList
    plural: metricsexporters
    singular: metricsexporter
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: summaryrules.adx-mon.azure.com
spec:
  group: adx-mon.azure.com
  names:
    kind: SummaryRule
    listKind: SummaryRuleList
    plural: summaryrules
    singular: summaryrule
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
